version: '3'
services:
  terraform:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    image: snowflake_terraform
    working_dir: /root/terraform/
    volumes:
      - .:/root/terraform/
      - ~/.ssh/snowflake/rsa_key.p8:/root/.ssh/rsa_key.p8
    env_file: .env
